# Generated by Django 6.0.7 on 2026-08-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_format',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('html', 'HTML')], default='markdown', max_length=10, verbose_name='内容格式'),
        ),
    ]
